server:
  port: 27020
  ssl:
    enabled: false
    key-alias: myhelper
    key-store: classpath:keystore/myhelper.keystore
    key-store-type: jks
    key-store-password: pwdpwd
    key-password: pwdpwd
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://yrd-postgres:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    data: classpath*:database/populateDB.sql
    initialization-mode: always
    schema: classpath*:database/initDB.sql
  security:
    oauth2:
      resource:
        filter-order: 3
