server:
  port: 27020
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://192.168.1.25:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    data: classpath*:database/populateDB.sql
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
